# playSound is <sound>,<volume>,<pitch>

jail:
  runMessage: §c§l%player%は「人のチェストからアイテムを取った」の理由でJailされました
  runCommand1: jail %player% moha 10
  runCommand2:
  runCommand3:
  playSound: block.anvil.land,1,1
warn:
  runMessage: §c§l%player%は「人のチェストからアイテムを取った」の理由で警告されました
  runCommand1: jail %player% moha 10
  runCommand2:
  runCommand3:
  playSound: block.anvil.land,1,1
mysql:
  host: localhost
  user: root
  pass: pass
  port: 3306
  db: world